In [2]:
import tensorflow as tf
import numpy as np
print(tf.__version__)

2.2.0


In [3]:
a = [10, 20, 30, 40, 50] #list
b = np.array(a) #list와 비슷, 그러나 comma가 없음
c = np.array([1, 3, 5])
print(a)
print(b)
print(c)

[10, 20, 30, 40, 50]
[10 20 30 40 50]
[1 3 5]


In [4]:
a = np.array([1, 2, 3, 4, 5])
b = a
c = a.copy()
b[0] = 99
print(a)
print(b)
print(c)

[99  2  3  4  5]
[99  2  3  4  5]
[1 2 3 4 5]


In [5]:
a = [1, 2, 3, 4, 5]
b = np.array(a)
c = np.array([1, 3, 5])

print(b[2])
print(c[-1])
print(c[0:2])

print(a*2) #list의 경우 해당 배열을 이어붙임.
print(b * 2) #numpy의 경우 각각의 원소로 계산하여 반환
print(c + 3)

3
5
[1 3]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 2  4  6  8 10]
[4 6 8]


In [6]:
#뒤에 자료형 명시(생략 시 데이터의 자료형을 유추, 자동으로 dtype 할당)
a = np.array([1, 2, 3], dtype = int)
b = np.array([1.1, 2.2, 3.3], dtype=float)
c = np.array([1, 1, 0], dtype = bool) #특정한 배열 생성 시 명시적으로 표기 필요

print(a)
print(b)
print(c)
print(a.dtype)

[1 2 3]
[1.1 2.2 3.3]
[ True  True False]
int32


In [7]:
a = np.array([[1, 2, 3],
             [4, 5, 6],
             [7, 8, 9]])
b = np.array([[[1, 2],
              [3, 4]],
             [[5, 6],
             [7, 8]],
             [[9, 10],
             [11, 12]]])
print(a)
print(b)
print(a[0][1])
print(b[0][1][1]) #[page][row][col]

print(a.ndim)
print(a.shape)
print(a.dtype)
print(np.ndim(b)) #dimension of array b
print(np.shape(b)) #(3, 2, 2) = (3 pages of 2 by 2 matrices)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
2
4
2
(3, 3)
int32
3
(3, 2, 2)


In [8]:
a = np.ones((2, 2), dtype = int) #shape of matrix
b = [1, 2, 3, 4, 5]
c = np.ones_like(b, dtype = int)

print(a)
print(b)
print(c)

[[1 1]
 [1 1]]
[1, 2, 3, 4, 5]
[1 1 1 1 1]


In [9]:
a = np.zeros((2, 2), dtype = int) #shape of matrix, dtype
b = [1, 2, 3, 4, 5]
c = np.zeros_like(b, dtype = int) #list or matrix, dtype

print(a)
print(b)
print(c)

[[0 0]
 [0 0]]
[1, 2, 3, 4, 5]
[0 0 0 0 0]


In [10]:
a = np.empty((2, 2), dtype = int) #shape of matrix
b = [1, 2, 3, 4, 5]
c = np.empty_like(b, dtype = int)

print(a)
print(b)
print(c)

[[1 1]
 [1 1]]
[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [11]:
a = np.identity(4, dtype = int) #4 by 4짜리 단위행렬
b = np.eye(4, 5, k = 1, dtype=int) #4 by 5크기의 K값만큼 이격된 단위행렬(k값이 양수이면 우상방향으로, 음수인경우 좌하방향으로 이동)
print(a)
print(b)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
[[0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [12]:
a = np.arange(0, 10, step=5) #start, end, 간격
b = np.arange(1, 10, step=5)
c = np.arange(0, 10, step=1)

print(a)
print(b)
print(c)

[0 5]
[1 6]
[0 1 2 3 4 5 6 7 8 9]


In [16]:
a = np.linspace(0, 10, num = 5, endpoint=True, retstep=True) #start, end, num=개수
#endpoint가 True일 경우 end의 값이 마지막이 됨
#False일 경우 end의 값을 마지막 값으로 사용하지 않음.
#retstep이 True일 경우 값들의 간격을 배열에 포함. arange()의 step과 같은 의미를 가짐
b = np.linspace(1, 10, num=5, endpoint=True, retstep=False)
c = np.linspace(0, 10, num = 5, endpoint=False, retstep=True)
print(a)
print(b)
print(c)

(array([ 0. ,  2.5,  5. ,  7.5, 10. ]), 2.5)
[ 1.    3.25  5.5   7.75 10.  ]
(array([0., 2., 4., 6., 8.]), 2.0)


In [20]:
#start, end, num=개수, endpoint=True/False, base=로그 값의 간격
a = np.logspace(0, 10, num=5, endpoint=True, base=10.0)
b = np.logspace(1, 10, num=5, endpoint = False, base = 5.0)

print(a)
print(b)

[1.00000000e+00 3.16227766e+02 1.00000000e+05 3.16227766e+07
 1.00000000e+10]
[5.00000000e+00 1.86918598e+02 6.98771243e+03 2.61226682e+05
 9.76562500e+06]


In [35]:
a = np.array([1, 2, 3, 4, 5])

print(a)
print('\n')
print(a[3:])
print('\n')
print(a[0:5:1])
print('\n')
print(a[1:-1])

[1 2 3 4 5]


[4 5]


[1 2 3 4 5]


[2 3 4]


In [36]:
a = np.array([
    [1, 2, 3],
    [4,5, 6],
    [7, 8, 9]
])
print(a)
print('\n')
print(a[:, 1:]) #: -> 모든 행에 대해, 1: -> 첫번째 열(0) 이후 모든 열에 대해 출력

[[1 2 3]
 [4 5 6]
 [7 8 9]]


[[2 3]
 [5 6]
 [8 9]]


In [40]:
a = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15]])

print(a[::2, ::2]) #행을 2칸씩 띄우며 열도 2칸씩 띄워 출력

[[1 4]]


In [42]:
a = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]])

print(np.shape(a)) #(행, 열)을 출력
a.shape = (6, 2) #6행 2열짜리 행렬로 형태변환. 단, 곱이 같아야 함(3*4 = 12 = 6*2)
print(a)

(3, 4)
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [44]:
a = np.array([[[1, 2, 3], 
               [4, 5, 6]],
              [[7, 8, 9], 
               [10, 11, 12]],
              [[13, 14, 15], 
               [16, 17, 18]]])

print(np.shape(a)) #3개의 2행 3열짜리 행렬들
a.shape = (2,3,3) #2*3*3 = 18 = 3*2*3
print(a)

(3, 2, 3)
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]
