In [1]:
import tensorflow as tf
import numpy as np
print(tf.__version__)

2.2.0


In [2]:
a = [10, 20, 30, 40, 50] #list
b = np.array(a) #list와 비슷, 그러나 comma가 없음
c = np.array([1, 3, 5])
print(a)
print(b)
print(c)

[10, 20, 30, 40, 50]
[10 20 30 40 50]
[1 3 5]


In [3]:
a = np.array([1, 2, 3, 4, 5])
b = a
c = a.copy()
b[0] = 99
print(a)
print(b)
print(c)

[99  2  3  4  5]
[99  2  3  4  5]
[1 2 3 4 5]


In [5]:
a = [1, 2, 3, 4, 5]
b = np.array(a)
c = np.array([1, 3, 5])

print(b[2])
print(c[-1])
print(c[0:2])

print(a*2) #list의 경우 해당 배열을 이어붙임.
print(b * 2) #numpy의 경우 각각의 원소로 계산하여 반환
print(c + 3)

3
5
[1 3]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 2  4  6  8 10]
[4 6 8]


In [6]:
#뒤에 자료형 명시(생략 시 데이터의 자료형을 유추, 자동으로 dtype 할당)
a = np.array([1, 2, 3], dtype = int)
b = np.array([1.1, 2.2, 3.3], dtype=float)
c = np.array([1, 1, 0], dtype = bool) #특정한 배열 생성 시 명시적으로 표기 필요

print(a)
print(b)
print(c)
print(a.dtype)

[1 2 3]
[1.1 2.2 3.3]
[ True  True False]
int32


In [8]:
a = np.array([[1, 2, 3],
             [4, 5, 6],
             [7, 8, 9]])
b = np.array([[[1, 2],
              [3, 4]],
             [[5, 6],
             [7, 8]],
             [[9, 10],
             [11, 12]]])
print(a)
print(b)
print(a[0][1])
print(b[0][1][1]) #[page][row][col]

print(a.ndim)
print(a.shape)
print(a.dtype)
print(np.ndim(b)) #dimension of array b
print(np.shape(b)) #(3, 2, 2) = (3 pages of 2 by 2 matrices)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
2
4
2
(3, 3)
int32
3
(3, 2, 2)
