In [2]:
import tensorflow as tf
import numpy as np
print(tf.__version__)

1.14.0


In [4]:
a = [10, 20, 30, 40, 50] #list
b = np.array(a) #list와 비슷, 그러나 comma가 없음
c = np.array([1, 3, 5])
d = np.array((1, 2, 3)) #tuple
e = np.array({1, 2, 3}) #dicitonary
print(a)
print(b)
print(c)
print(d)
print(e)

[10, 20, 30, 40, 50]
[10 20 30 40 50]
[1 3 5]
[1 2 3]
{1, 2, 3}


In [4]:
a = np.array([1, 2, 3, 4, 5])
b = a
c = a.copy()
b[0] = 99
print(a)
print(b)
print(c)

[99  2  3  4  5]
[99  2  3  4  5]
[1 2 3 4 5]


In [5]:
a = [1, 2, 3, 4, 5]
b = np.array(a)
c = np.array([1, 3, 5])

print(b[2])
print(c[-1])
print(c[0:2])

print(a*2) #list의 경우 해당 배열을 이어붙임.
print(b * 2) #numpy의 경우 각각의 원소로 계산하여 반환
print(c + 3)

3
5
[1 3]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 2  4  6  8 10]
[4 6 8]


In [6]:
#뒤에 자료형 명시(생략 시 데이터의 자료형을 유추, 자동으로 dtype 할당)
a = np.array([1, 2, 3], dtype = int)
b = np.array([1.1, 2.2, 3.3], dtype=float)
c = np.array([1, 1, 0], dtype = bool) #특정한 배열 생성 시 명시적으로 표기 필요

print(a)
print(b)
print(c)
print(a.dtype)

[1 2 3]
[1.1 2.2 3.3]
[ True  True False]
int32


In [9]:
a = np.array([[1, 2, 3],
             [4, 5, 6],
             [7, 8, 9]])
b = np.array([[[1, 2],
              [3, 4]],
             [[5, 6],
             [7, 8]],
             [[9, 10],
             [11, 12]]])
print(a)
print()
print(b)
print("a[0][1]: " + str(a[0][1]))
print("b[0][1][1]: " + str(b[0][1][1])) #[page][row][col]

print("Dimension of a:" + str(a.ndim))
print("Shape of a:" + str(a.shape))
print("Type of a: " + str(a.dtype))
print(np.ndim(b)) #dimension of array b
print(np.shape(b)) #(3, 2, 2) = (3 pages of 2 by 2 matrices)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
a[0][1]: 2
b[0][1][1]: 4
Dimension of a:2
Shape of a:(3, 3)
Type of a: int32
3
(3, 2, 2)


In [12]:
#numpy.dot
#1-d array의 경우: dot(inner) product(내적) of two vectors
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.dot(a, b)
print(c)

#2-d array의 경우: 행렬곱을 한다
a = np.array([[1, 2],
              [3, 4]])
b = np.array([[-2, -1, 0],
             [0, 1, 2]])
print(np.dot(a, b))

#scalar의 경우: 일반 곱셈. a*b 및 np.multiply로 대체가능
a = 3
b = 5
print(np.dot(a, b))

32
[[-2  1  4]
 [-6  1  8]]
15


In [8]:
a = np.ones((2, 2), dtype = int) #shape of matrix
b = [1, 2, 3, 4, 5]
c = np.ones_like(b, dtype = int)

print(a)
print(b)
print(c)

[[1 1]
 [1 1]]
[1, 2, 3, 4, 5]
[1 1 1 1 1]


In [9]:
a = np.zeros((2, 2), dtype = int) #shape of matrix, dtype
b = [1, 2, 3, 4, 5]
c = np.zeros_like(b, dtype = int) #list or matrix, dtype

print(a)
print(b)
print(c)

[[0 0]
 [0 0]]
[1, 2, 3, 4, 5]
[0 0 0 0 0]


In [10]:
a = np.empty((2, 2), dtype = int) #shape of matrix
b = [1, 2, 3, 4, 5]
c = np.empty_like(b, dtype = int)

print(a)
print(b)
print(c)

[[1 1]
 [1 1]]
[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [11]:
a = np.identity(4, dtype = int) #4 by 4짜리 단위행렬
b = np.eye(4, 5, k = 1, dtype=int) #4 by 5크기의 K값만큼 이격된 단위행렬(k값이 양수이면 우상방향으로, 음수인경우 좌하방향으로 이동)
print(a)
print(b)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
[[0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [12]:
a = np.arange(0, 10, step=5) #start, end, 간격
b = np.arange(1, 10, step=5)
c = np.arange(0, 10, step=1)

print(a)
print(b)
print(c)

[0 5]
[1 6]
[0 1 2 3 4 5 6 7 8 9]


In [16]:
a = np.linspace(0, 10, num = 5, endpoint=True, retstep=True) #start, end, num=개수
#endpoint가 True일 경우 end의 값이 마지막이 됨
#False일 경우 end의 값을 마지막 값으로 사용하지 않음.
#retstep이 True일 경우 값들의 간격을 배열에 포함. arange()의 step과 같은 의미를 가짐
b = np.linspace(1, 10, num=5, endpoint=True, retstep=False)
c = np.linspace(0, 10, num = 5, endpoint=False, retstep=True)
print(a)
print(b)
print(c)

(array([ 0. ,  2.5,  5. ,  7.5, 10. ]), 2.5)
[ 1.    3.25  5.5   7.75 10.  ]
(array([0., 2., 4., 6., 8.]), 2.0)


In [20]:
#start, end, num=개수, endpoint=True/False, base=로그 값의 간격
a = np.logspace(0, 10, num=5, endpoint=True, base=10.0)
b = np.logspace(1, 10, num=5, endpoint = False, base = 5.0)

print(a)
print(b)

[1.00000000e+00 3.16227766e+02 1.00000000e+05 3.16227766e+07
 1.00000000e+10]
[5.00000000e+00 1.86918598e+02 6.98771243e+03 2.61226682e+05
 9.76562500e+06]


In [35]:
a = np.array([1, 2, 3, 4, 5])

print(a)
print('\n')
print(a[3:])
print('\n')
print(a[0:5:1])
print('\n')
print(a[1:-1])

[1 2 3 4 5]


[4 5]


[1 2 3 4 5]


[2 3 4]


In [36]:
a = np.array([
    [1, 2, 3],
    [4,5, 6],
    [7, 8, 9]
])
print(a)
print('\n')
print(a[:, 1:]) #: -> 모든 행에 대해, 1: -> 첫번째 열(0) 이후 모든 열에 대해 출력

[[1 2 3]
 [4 5 6]
 [7 8 9]]


[[2 3]
 [5 6]
 [8 9]]


In [40]:
a = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15]])

print(a[::2, ::2]) #행을 2칸씩 띄우며 열도 2칸씩 띄워 출력

[[1 4]]


In [42]:
a = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]])

print(np.shape(a)) #(행, 열)을 출력
a.shape = (6, 2) #6행 2열짜리 행렬로 형태변환. 단, 곱이 같아야 함(3*4 = 12 = 6*2)
print(a)

(3, 4)
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [44]:
a = np.array([[[1, 2, 3], 
               [4, 5, 6]],
              [[7, 8, 9], 
               [10, 11, 12]],
              [[13, 14, 15], 
               [16, 17, 18]]])

print(np.shape(a)) #3개의 2행 3열짜리 행렬들
a.shape = (2,3,3) #2*3*3 = 18 = 3*2*3
print(a)

(3, 2, 3)
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


In [15]:
#random값으로 된 2x3행렬을 생성
np.random.rand(2, 3)

array([[0.98718966, 0.50845591, 0.59418092],
       [0.72689784, 0.09492857, 0.38339444]])

In [13]:
a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

b = np.ones(3, dtype = int) #1로만 된 1x3 배열생성
print(a)
print(b)
#사칙연산 관련 연산들은 array와 array사이에 연산기호를 포함해 계산 가능.
#혼합계산의 경우 일반 수식과 동일하게 곱하기(*)와 나누기(/) 먼저 수행
'''
print(a + b)
print(a - b)
print(a * b)
print(a / b)
'''
print(np.cross(a, b))#벡터곱
print(np.dot(a, b))#점곱

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 1 1]
[[-1  2 -1]
 [-1  2 -1]
 [-1  2 -1]]
[ 6 15 24]


In [15]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[1, 3], [2, 4]])
#array끼리 곱하는 경우
print(a*b) #각 원소끼리 곱연산(A11은 B11과 곱, A22는 B22와 곱...)

#행렬끼리 곱하는 경우
ma = np.mat(a)
mb = np.mat(b)
print(ma*mb) #행렬 곱연산

[[ 1  6]
 [ 6 16]]
[[ 5 11]
 [11 25]]


In [16]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[1-1j, 2-1j], [3, 4]])
c = np.array([[1, 3], [2, 4]])
d = np.array([[1, 3], [2, 4]])

ma = np.mat(a).T #해당 행렬의 전치(transpose) 리턴
mb = np.mat(b).H #공액복소수의 전치값 반환
mc = np.mat(c).I #곱의 역함수(inverse)
md = np.mat(d).A #다시 array형식으로 변환 후 반환

print(ma)
print(mb)
print(mc)
print(md)

[[1 3]
 [2 4]]
[[1.+1.j 3.-0.j]
 [2.+1.j 4.-0.j]]
[[-2.   1.5]
 [ 1.  -0.5]]
[[1 3]
 [2 4]]


In [25]:
arr1 = np.array([1, 2, 3, 4])
newmat = np.mat(arr1).T
print(newmat.shape)
print(newmat.ndim)
print(newmat)

(4, 1)
2
[[1 2 3 4]]


In [33]:
arr = np.array([1, 2, 3, 4])
print(arr)
print(arr.ndim)
print(arr[np.newaxis]) #새로운 축 추가
print(arr[np.newaxis].ndim)
print(arr[:, np.newaxis])

[1 2 3 4]
1
[[1 2 3 4]]
2
[[1]
 [2]
 [3]
 [4]]


In [39]:
arr = np.array([[1, 2],
               [3, 4]], dtype=int)
new_arr = arr[:, np.newaxis] #차원(축) 추가
print(arr.ndim)
print(new_arr)
print(new_arr[1][0])
print(new_arr[1][0][1])

2
[[[1 2]]

 [[3 4]]]
[3 4]
4


In [46]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])
print(arr1[np.newaxis] * arr2)
print(arr1[:, np.newaxis] * arr2)

[[1 4 9]]
[[1 2 3]
 [2 4 6]
 [3 6 9]]


In [48]:
arr = np.array([[1], [2], [3]])
print(arr)
print(np.expand_dims(arr, axis=0)) #차원 확장
print(np.squeeze(arr, axis=1))#차원 축소

[[1]
 [2]
 [3]]
[[[1]
  [2]
  [3]]]
[1 2 3]


In [49]:
np.random.seed(76923) #임의의 시드 생성
#시드값에 따라 난수와 흡사하나 항상 같은 결과를 반환함
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

#배열에서 n(5)개의 값을 선택하여 반환가능
#replace=True일 경우, 값이 중복되어 선택돼 반환 될 수 있음
#replace=False일 경우, 값이 중복되지 않음
#p를 이용해 각 데이터가 선택될 확률을 설정할 수 있음
#따라서 p배열의 길이는 항상 해당 배열의 길이와 동일해야 함
#p값들의 총 합은 항상 1이어야 하며, replace를 False로 사용할 경우,
#값이 중복되지 않기 때문에 n개이상 0의 값과 달라야 함.
b = np.random.choice(a, 5, replace=False, p=[0, 0, 0, 0, 0.05, 0.05, 0.05, 0.05, 0.8])
print(b)

[9 5 6 7 8]


In [59]:
np.random.seed(76923)

a = np.random.rand(2, 2)#다차원 무작위 배열 생성
print(a)
#표준정규분포에서 무작위 배열 생성
b = np.random.randn(2, 2)
print(c)
#low~high-1 사이 무작위 nxm크기의 정수배열을 생성
c = np.random.randint(1, 3, (2, 2), dtype=int)
print(c)

[[0.76367992 0.87641303]
 [0.53095238 0.38451373]]
[[1 1]
 [2 1]]
[[1 1]
 [2 1]]


In [61]:
np.random.seed(76923)

#low와 high사이의 균일한 분포의 무작위 배열을 반환함.
a = np.random.uniform(1, 2, (2, 2)) 
print(a)
#mean = 3, sigma = 1, size = (2, 2)
b = np.random.lognormal(3, 1, (2, 2)) 
print(b)
#뮤와 람다를 대입한 라플라스 분포의 무작위 배열 생성
c = np.random.laplace(0, 1, (2, 2)) 
print(c)

[[1.76367992 1.87641303]
 [1.53095238 1.38451373]]
[[ 17.12791367  18.54480749]
 [114.18014024  12.4912986 ]]
[[ 0.09286726  0.67469586]
 [ 1.56654873 -0.32583306]]


In [62]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
c = np.hstack([a, b]) #해당 배열(a)의 우측에 이어붙임
d = np.vstack([a, b]) #해당 배열(a)의 하단에 이어붙임
print(c)
print(d)

[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


In [63]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
c = np.stack([a, b], axis=0) #지정한 축으로 배열 이어붙임
d = np.stack([a, b], axis=1)
print(c)
print(d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


In [64]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
c = np.dstack([a, b])
print(c)

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [65]:
a = np.array([[1, 2], [3, 4]])
b = np.tile(a, 2) #배열을 2회 반복하여 이어붙임

print(a)
print(b)

[[1 2]
 [3 4]]
[[1 2 1 2]
 [3 4 3 4]]


In [67]:
#numpy broadcasting
'''
일반적으로 넘파이에서 모양(shape)이 다른 배열끼린
연산이 불가능함
따라서 numpy배열에서 차원의 크기가 서로 다른 배열에서도 산술연산을
가능케 하는 원리임
두 배열 간 차원크기가 (4, 2), (2,)일때 산술연산을 실행한다면
(2,)의 배열이 (4, 2)행렬의 각 행에 대해 요소별 연산을 실행할 수 있음

브로드캐스팅 허용 규칙
-두 배열의 차원이 같지 않다면 차원이 
더 낮은 배열이 차원이 더 높은 배열과 같은 차원의 배열로 인식됨.
-반환된 배열은 연산을 수행한 배열 중 차원의 수가 가장 큰 배열이 됨
-연산에 사용된 배열과 반환된 배열의 차원크기가 같거나 1일 경우
브로드캐스팅 가능
-브로드캐스팅이 적용된 배열의 차원크기는 연산에 사용된 배열들의 차원의
크기에 대한 최소공배수 값으로 사용함.
'''
array1 = np.array([1, 2, 3, 4]).reshape(2, 2)
print(array1.ndim)
array2 = np.array([1.5, 2.5])
print(array2.ndim)
#서로 차원이 달라도 브로드캐스팅 허용규칙에 
#위반되지 않는다면 연산이 가능하다
print(array1 + array2)

2
1
[[2.5 4.5]
 [4.5 6.5]]


In [81]:
a = np.array([[1, 2], [3, 4]])
b =  np.array([[2] ,[3]])
ma = np.mat(a)
mb = np.mat(b)
print(a * b.T)
print(ma.reshape(4, 1) * mb.T)

[[ 2  6]
 [ 6 12]]
[[ 2  3]
 [ 4  6]
 [ 6  9]
 [ 8 12]]
